export const POST_LIST_REQUEST = 'POST_LIST_REQUEST';
export const POST_LIST_SUCESS = 'POST_LIST_SUCESS';
export const POST_LIST_FAIL = 'POST_LIST_FAIL';

export const POST_DETAILS_REQUEST = 'POST_DETAILS_REQUEST';
export const POST_DETAILS_SUCESS = 'POST_DETAILS_SUCESS';
export const POST_DETAILS_FAIL = 'POST_DETAILS_FAIL';

export const POST_LIKE_ADD = 'POST_LIKE_ITEM';
export const POST_LIKE_REMOVE = 'POST_LIKE_REMOVE'; 