export const POST_LIST_REQUEST = 'POST_LIST_REQUEST';
export const POST_LIST_SUCESS = 'POST_LIST_SUCESS';
export const POST_LIST_FAIL = 'POST_LIST_FAIL';

export const POST_DETAILS_REQUEST = 'POST_DETAILS_REQUEST';
export const POST_DETAILS_SUCESS = 'POST_DETAILS_SUCESS';
export const POST_DETAILS_FAIL = 'POST_DETAILS_FAIL';

export const POST_DELETE_REQUEST = 'POST_DELETE_REQUEST';
export const POST_DELETE_SUCESS = 'POST_DELETE_SUCESS';
export const POST_DELETE_FAIL = 'POST_DELETE_FAIL';

export const POST_LIKE_ADD = 'POST_LIKE_ITEM';
export const POST_LIKE_REMOVE = 'POST_LIKE_REMOVE'; 

export const POST_CREATE_REQUEST = 'POST_CREATE_REQUEST';
export const POST_CREATE_SUCESS = 'POST_CREATE_SUCESS';
export const POST_CREATE_FAIL = 'POST_CREATE_FAIL';
export const POST_CREATE_RESET = 'POST_CREATE_RESET';

export const POST_UPDATE_REQUEST = 'POST_UPDATE_REQUEST';
export const POST_UPDATE_SUCESS = 'POST_UPDATE_SUCESS';
export const POST_UPDATE_FAIL = 'POST_UPDATE_FAIL';
export const POST_UPDATE_RESET = 'POST_UPDATE_RESET';

export const POST_CREATE_REVIEW_REQUEST = 'POST_CREATE_REVIEW_REQUEST';
export const POST_CREATE_REVIEW_SUCESS = 'POST_CREATE_REVIEW_SUCESS';
export const POST_CREATE_REVIEW_FAIL = 'POST_CREATE_REVIEW_FAIL';
export const POST_CREATE_REVIEW_RESET = 'POST_CREATE_REVIEW_RESET';

export const POST_LIST_OF_USER_REQUEST = 'POST_LIST_OF_USER_REQUEST';
export const POST_LIST_OF_USER_SUCCESS = 'POST_LIST_OF_USER_SUCCESS';
export const POST_LIST_OF_USER_FAIL = 'POST_LIST_OF_USER_FAIL';
